<?php

namespace AppBundle\Repository;

/**
 * CodigoPostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodigoPostalRepository extends \Doctrine\ORM\EntityRepository
{
}
