drop table categoria cascade;
drop table ciudad cascade;
drop table contacto_tipo cascade;
drop table documento_tipo cascade;
drop table domicilio_tipo cascade;
drop table estado cascade;
drop table fos_group cascade;
drop table fos_user cascade;
drop table fos_user_user_group cascade;
drop table idioma cascade;
drop table legajo cascade;
drop table menu cascade;
drop table migration_versions cascade;
drop table pais cascade;
drop table producto cascade;
drop table provincia cascade;
drop table region cascade;
drop table roles cascade;
drop table route cascade;
drop table routes_roles cascade;
drop table shipper cascade;
drop table zona cascade;
drop table subzona cascade;
drop table sucursal cascade;
drop table tarifario cascade;
drop table transporte cascade;
drop table upload cascade;
drop table persona cascade;
drop table persona_categoria cascade;
drop table persona_contacto cascade;
drop table persona_documento cascade;
drop table persona_domicilio cascade;
drop table persona_idioma cascade;
drop table file_structure_shipper cascade;
drop table file_structure_std cascade;
drop table original_file cascade;
drop table shipper_original cascade;

drop sequence fos_group_id_seq;
drop sequence fos_user_id_seq;
drop sequence menu_id_menu_seq;
drop sequence upload_id_seq;
drop sequence ciudad_id_ciudad_seq;
drop sequence pais_id_pais_seq;
drop sequence provincia_id_provincia_seq;
drop sequence region_id_region_seq;
drop sequence sucursal_id_sucursal_seq;
drop sequence shipper_id_shipper_seq;
drop sequence producto_id_producto_seq;
drop sequence subzona_id_subzona_seq;
drop sequence zona_id_zona_seq;
drop sequence roles_id_seq;
drop sequence categoria_id_categoria_seq;
drop sequence contacto_tipo_id_contacto_tipo_seq;
drop sequence documento_tipo_id_documento_tipo_seq;
drop sequence domicilio_tipo_id_domicilio_tipo_seq;
drop sequence idioma_id_idioma_seq;
drop sequence legajo_id_legajo_seq;
drop sequence persona_id_persona_seq;
drop sequence persona_categoria_id_persona_categoria_seq;
drop sequence persona_contacto_id_persona_contacto_seq;
drop sequence persona_documento_id_persona_documento_seq;
drop sequence persona_domicilio_id_persona_domicilio_seq;
drop sequence persona_idioma_id_persona_idioma_seq;
drop sequence tarifario_id_tarifario_seq;
drop sequence transporte_id_transporte_seq;
drop sequence estado_id_estado_seq;
drop sequence route_id_route_seq;
drop sequence file_structure_shipper_id_seq;
drop sequence file_structure_std_id_seq;
drop sequence original_file_id_seq;
drop sequence shipper_original_id_seq;



