app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"   
    
# app/config/routing.yml    
fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group
    
consultas:
    resource: '@AppBundle/Ajax/'
    type: annotation
    
